"""create ticket schema

Revision ID: 31be9023cfb2
Revises: 6a3066cd5538
Create Date: 2026-09-30 20:34:14.437324

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31be9023cfb2"
down_revision: Union[str, Sequence[str], None] = "6a3066cd5538"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column(
            "ticket_id", sa.BigInteger(), sa.Identity(always=True), nullable=False
        ),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("requester_membership_id", sa.BigInteger(), nullable=False),
        sa.Column("creator_membership_id", sa.BigInteger(), nullable=False),
        sa.Column("assignee_membership_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'open'"), nullable=False
        ),
        sa.Column(
            "priority", sa.Text(), server_default=sa.text("'medium'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'urgent')",
            name="ck_tickets_priority",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'resolved', 'closed')",
            name="ck_tickets_status",
        ),
        sa.CheckConstraint(
            "char_length(description) BETWEEN 1 AND 10000",
            name="ck_tickets_description_length",
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 255", name="ck_tickets_title_length"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "assignee_membership_id"],
            [
                "organization_memberships.organization_id",
                "organization_memberships.membership_id",
            ],
            name="fk_tickets_assignee_membership",
            ondelete="RESTRICT",
            match="SIMPLE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "creator_membership_id"],
            [
                "organization_memberships.organization_id",
                "organization_memberships.membership_id",
            ],
            name="fk_tickets_creator_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "requester_membership_id"],
            [
                "organization_memberships.organization_id",
                "organization_memberships.membership_id",
            ],
            name="fk_tickets_requester_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.organization_id"],
            name="fk_tickets_organization_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("ticket_id", name="pk_tickets"),
        sa.UniqueConstraint(
            "organization_id", "ticket_id", name="uq_tickets_org_ticket"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets")
    # ### end Alembic commands ###
