"""create initial identity and organization schema

Revision ID: 6a3066cd5538
Revises:
Create Date: 2026-09-17 20:49:01.111552

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a3066cd5538"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column(
            "organization_id", sa.BigInteger(), sa.Identity(always=True), nullable=False
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 255", name="ck_organizations_name_length"
        ),
        sa.PrimaryKeyConstraint("organization_id", name="pk_organizations"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.CheckConstraint(
            "char_length(email) BETWEEN 1 AND 254", name="ck_users_email_length"
        ),
        sa.CheckConstraint(
            "email COLLATE \"C\" !~ '[A-Z]'", name="ck_users_email_lowercase"
        ),
        sa.CheckConstraint(
            "email COLLATE \"C\" ~ '^[!-~]+$'", name="ck_users_email_ascii_nonspace"
        ),
        sa.PrimaryKeyConstraint("user_id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_table(
        "organization_memberships",
        sa.Column(
            "membership_id", sa.BigInteger(), sa.Identity(always=True), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'agent', 'customer')",
            name="ck_memberships_role",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.organization_id"],
            name="fk_memberships_organization_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="fk_memberships_user_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("membership_id", name="pk_organization_memberships"),
        sa.UniqueConstraint(
            "organization_id", "membership_id", name="uq_memberships_org_membership"
        ),
        sa.UniqueConstraint(
            "user_id", "organization_id", name="uq_memberships_user_org"
        ),
    )
    op.create_index(
        "uq_memberships_active_owner_per_org",
        "organization_memberships",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("role = 'owner' AND is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_memberships_active_owner_per_org",
        table_name="organization_memberships",
        postgresql_where=sa.text("role = 'owner' AND is_active = true"),
    )
    op.drop_table("organization_memberships")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
